/**
 * Catalogue de permissions et rôles système, miroir exact de ce qui est réellement
 * seedé par db/schema.sql §21 (SEED RBAC) et par le trigger `bootstrap_organization()`
 * (§4B) sur le projet Supabase live. `role_permissions` (association rôle → permission)
 * n'est PAS encore seedée côté base — c'est fait par db/seed/index.ts (Phase 3+),
 * en utilisant ROLE_PERMISSIONS ci-dessous comme unique source de vérité côté code.
 */

export const SYSTEM_ROLES = [
  "SUPER_ADMIN",
  "CHURCH_OWNER",
  "PASTOR",
  "PASTORAL_LEADER",
  "MINISTRY_LEADER",
  "FINANCE_MANAGER",
  "SECRETARY",
  "WORKER",
  "MEMBER",
] as const;

export type SystemRole = (typeof SYSTEM_ROLES)[number];

export interface PermissionDef {
  code: string;
  name: string;
  module: string;
  description: string;
}

/** Exactement les lignes de db/schema.sql §21 (insert into public.permissions ...). */
export const PERMISSIONS: PermissionDef[] = [
  { code: "members.view", name: "Voir les membres", module: "members", description: "Consulter les membres" },
  { code: "members.create", name: "Créer des membres", module: "members", description: "Créer un membre" },
  { code: "members.update", name: "Modifier les membres", module: "members", description: "Modifier un membre" },
  { code: "members.delete", name: "Supprimer les membres", module: "members", description: "Supprimer un membre" },
  { code: "pastoral.view", name: "Voir le pastoral", module: "pastoral", description: "Consulter le suivi pastoral" },
  { code: "pastoral.create", name: "Créer un suivi pastoral", module: "pastoral", description: "Créer un suivi" },
  { code: "pastoral.update", name: "Modifier le pastoral", module: "pastoral", description: "Modifier un suivi" },
  { code: "pastoral.delete", name: "Supprimer le pastoral", module: "pastoral", description: "Supprimer un suivi" },
  { code: "pastoral.view_confidential", name: "Voir le pastoral confidentiel", module: "pastoral", description: "Voir les suivis pastoraux et sujets de prière marqués confidentiels" },
  { code: "prayer.view", name: "Voir les prières", module: "prayer", description: "Consulter les sujets de prière" },
  { code: "prayer.create", name: "Créer une prière", module: "prayer", description: "Créer un sujet" },
  { code: "prayer.update", name: "Modifier les prières", module: "prayer", description: "Modifier un sujet" },
  { code: "visits.view", name: "Voir les visites", module: "visits", description: "Consulter les visites pastorales" },
  { code: "visits.create", name: "Créer des visites", module: "visits", description: "Planifier ou enregistrer une visite" },
  { code: "visits.update", name: "Modifier les visites", module: "visits", description: "Modifier une visite" },
  { code: "pastoral_council.view", name: "Voir le conseil pastoral", module: "pastoral_council", description: "Consulter les réunions du conseil pastoral" },
  { code: "pastoral_council.manage", name: "Gérer le conseil pastoral", module: "pastoral_council", description: "Créer/modifier les réunions, membres et actions du conseil pastoral" },
  { code: "ministries.view", name: "Voir les ministères", module: "ministries", description: "Consulter les ministères" },
  { code: "ministries.create", name: "Créer des ministères", module: "ministries", description: "Créer un ministère" },
  { code: "ministries.update", name: "Modifier les ministères", module: "ministries", description: "Modifier un ministère" },
  { code: "teams.view", name: "Voir les équipes", module: "teams", description: "Consulter les équipes" },
  { code: "teams.create", name: "Créer des équipes", module: "teams", description: "Créer une équipe" },
  { code: "teams.update", name: "Modifier les équipes", module: "teams", description: "Modifier une équipe" },
  { code: "workers.view", name: "Voir les ouvriers", module: "workers", description: "Consulter les ouvriers" },
  { code: "workers.create", name: "Créer des ouvriers", module: "workers", description: "Enregistrer un ouvrier" },
  { code: "workers.update", name: "Modifier les ouvriers", module: "workers", description: "Modifier un ouvrier" },
  { code: "services.view", name: "Voir les services", module: "services", description: "Consulter les services (cultes)" },
  { code: "services.create", name: "Créer des services", module: "services", description: "Créer un service et ses affectations" },
  { code: "services.update", name: "Modifier les services", module: "services", description: "Modifier un service ou ses affectations" },
  { code: "planning.view", name: "Voir les plannings", module: "planning", description: "Consulter les créneaux de planning" },
  { code: "planning.create", name: "Créer des créneaux de planning", module: "planning", description: "Créer un créneau de planning" },
  { code: "planning.update", name: "Modifier les plannings", module: "planning", description: "Modifier un créneau de planning" },
  { code: "events.view", name: "Voir les événements", module: "events", description: "Consulter les événements" },
  { code: "events.create", name: "Créer des événements", module: "events", description: "Créer un événement" },
  { code: "events.update", name: "Modifier les événements", module: "events", description: "Modifier un événement" },
  { code: "events.delete", name: "Supprimer les événements", module: "events", description: "Supprimer un événement" },
  { code: "attendance.view", name: "Voir les présences", module: "attendance", description: "Consulter les présences" },
  { code: "attendance.create", name: "Saisir les présences", module: "attendance", description: "Enregistrer une présence" },
  { code: "registrations.view", name: "Voir les inscriptions", module: "registrations", description: "Consulter les inscriptions aux événements" },
  { code: "registrations.create", name: "Créer des inscriptions", module: "registrations", description: "Inscrire une personne ou un invité à un événement" },
  { code: "registrations.update", name: "Modifier les inscriptions", module: "registrations", description: "Modifier le statut d'une inscription" },
  { code: "calendar.view", name: "Voir le calendrier", module: "calendar", description: "Consulter le calendrier agrégé" },
  { code: "calendar.manage", name: "Gérer le calendrier", module: "calendar", description: "Créer/modifier des entrées de calendrier manuelles" },
  { code: "finance.view", name: "Voir les finances", module: "finance", description: "Consulter les finances" },
  { code: "finance.create", name: "Créer une opération financière", module: "finance", description: "Créer une opération" },
  { code: "finance.approve", name: "Approuver une opération", module: "finance", description: "Approuver une opération" },
  { code: "reports.view", name: "Voir les rapports", module: "reports", description: "Consulter les rapports" },
  { code: "reports.export", name: "Exporter les rapports", module: "reports", description: "Exporter les rapports" },
  { code: "training.view", name: "Voir les formations", module: "training", description: "Consulter les cours, modules, inscriptions et certifications" },
  { code: "training.manage", name: "Gérer les formations", module: "training", description: "Créer/modifier les cours et leurs modules" },
  { code: "training.enroll", name: "Gérer les inscriptions aux cours", module: "training", description: "Inscrire une personne à un cours, modifier statut/progression" },
  { code: "training.certify", name: "Délivrer des certifications", module: "training", description: "Émettre une certification pour une personne" },
  { code: "certifications.view", name: "Voir les certifications", module: "certifications", description: "Consulter la page des certifications et les certifications visibles" },
  { code: "library.view", name: "Voir la bibliothèque", module: "library", description: "Consulter, lire et télécharger les ressources de la bibliothèque" },
  { code: "library.manage", name: "Gérer la bibliothèque", module: "library", description: "Ajouter, modifier et supprimer les ressources et leurs catégories" },
  { code: "communication.view", name: "Voir les communications", module: "communication", description: "Consulter les annonces, modèles et l'historique d'envoi" },
  { code: "communication.manage", name: "Gérer les communications", module: "communication", description: "Créer/modifier les annonces et les modèles de message" },
  { code: "messages.view", name: "Voir les messages SMS/Email", module: "messages", description: "Consulter les messages envoyés, planifiés et brouillons" },
  { code: "messages.send", name: "Envoyer des messages SMS/Email", module: "messages", description: "Composer, planifier et envoyer des SMS et des emails" },
  { code: "media.view", name: "Voir les médias", module: "media", description: "Consulter les photos, vidéos, audios et documents" },
  { code: "media.manage", name: "Gérer les médias", module: "media", description: "Ajouter, modifier et supprimer des médias, relier la chaîne YouTube" },
  { code: "documents.view", name: "Voir les documents", module: "documents", description: "Consulter les dossiers et documents" },
  { code: "documents.manage", name: "Gérer les documents", module: "documents", description: "Créer des dossiers, téléverser et supprimer des documents" },
  { code: "rooms.view", name: "Voir les salles", module: "rooms", description: "Consulter les salles et leur disponibilité" },
  { code: "rooms.manage", name: "Gérer les salles", module: "rooms", description: "Créer, modifier et supprimer des salles" },
  { code: "rooms.reserve", name: "Réserver une salle", module: "rooms", description: "Créer et gérer une réservation de salle" },
  { code: "equipment.view", name: "Voir les équipements", module: "equipment", description: "Consulter les équipements et leur affectation" },
  { code: "equipment.manage", name: "Gérer les équipements", module: "equipment", description: "Créer, modifier et supprimer des équipements" },
  { code: "equipment.reserve", name: "Réserver un équipement", module: "equipment", description: "Créer et gérer une réservation d'équipement" },
  { code: "settings.manage", name: "Gérer les paramètres", module: "settings", description: "Administrer ChurchOS" },
];

export type PermissionCode = (typeof PERMISSIONS)[number]["code"];

const ALL = PERMISSIONS.map((p) => p.code);

function only(...codes: string[]): string[] {
  return codes;
}

/**
 * Pas encore seedée en base (voir note d'en-tête) — c'est la proposition ChurchOS,
 * appliquée par db/seed/index.ts. `is_org_admin()` (SUPER_ADMIN/CHURCH_OWNER) contourne
 * de toute façon `role_permissions` dans les policies RLS génériques (voir db/schema.sql
 * §20), donc ces deux rôles n'ont pas besoin d'y figurer pour avoir accès complet.
 */
export const ROLE_PERMISSIONS: Record<SystemRole, string[]> = {
  SUPER_ADMIN: ALL,
  CHURCH_OWNER: ALL,

  PASTOR: ALL.filter((c) => c !== "settings.manage"),

  PASTORAL_LEADER: only(
    "members.view",
    "pastoral.view",
    "pastoral.create",
    "pastoral.update",
    "pastoral.view_confidential",
    "prayer.view",
    "prayer.create",
    "prayer.update",
    "visits.view",
    "visits.create",
    "visits.update",
    "pastoral_council.view",
    "pastoral_council.manage",
    "events.view",
    "attendance.view",
    "reports.view",
    "training.view",
    "certifications.view",
    "library.view",
    "training.manage",
    "library.manage",
    "training.enroll",
    "training.certify",
    "communication.view",
    "messages.view",
    "media.view",
    "documents.view",
    "rooms.view",
    "equipment.view",
    "rooms.reserve",
    "equipment.reserve",
  ),

  MINISTRY_LEADER: only(
    "members.view",
    "ministries.view",
    "ministries.create",
    "ministries.update",
    "teams.view",
    "teams.create",
    "teams.update",
    "workers.view",
    "workers.create",
    "workers.update",
    "services.view",
    "services.create",
    "services.update",
    "planning.view",
    "planning.create",
    "planning.update",
    "events.view",
    "events.create",
    "events.update",
    "attendance.view",
    "attendance.create",
    "registrations.view",
    "registrations.create",
    "registrations.update",
    "calendar.view",
    "calendar.manage",
    "reports.view",
    "training.view",
    "certifications.view",
    "library.view",
    "communication.view",
    "messages.view",
    "media.view",
    "documents.view",
    "rooms.view",
    "equipment.view",
    "rooms.reserve",
    "equipment.reserve",
  ),

  FINANCE_MANAGER: only(
    "members.view",
    "finance.view",
    "finance.create",
    "finance.approve",
    "reports.view",
    "reports.export",
  ),

  SECRETARY: only(
    "members.view",
    "members.create",
    "members.update",
    "events.view",
    "events.create",
    "events.update",
    "attendance.view",
    "attendance.create",
    "registrations.view",
    "registrations.create",
    "registrations.update",
    "calendar.view",
    "reports.view",
    "training.view",
    "certifications.view",
    "library.view",
    "training.enroll",
    "communication.view",
    "messages.view",
    "media.view",
    "communication.manage",
    "media.manage",
    "messages.send",
    "documents.view",
    "documents.manage",
    "rooms.view",
    "equipment.view",
    "rooms.manage",
    "equipment.manage",
    "rooms.reserve",
    "equipment.reserve",
  ),

  WORKER: only(
    "members.view",
    "services.view",
    "planning.view",
    "events.view",
    "attendance.view",
    "attendance.create",
    "registrations.view",
    "calendar.view",
    "training.view",
    "certifications.view",
    "library.view",
    "training.enroll",
    "communication.view",
    "messages.view",
    "media.view",
    "documents.view",
    "rooms.view",
    "equipment.view",
    "rooms.reserve",
    "equipment.reserve",
  ),

  MEMBER: only(
    "events.view",
    "registrations.create",
    "calendar.view",
    "training.view",
    "certifications.view",
    "library.view",
    "training.enroll",
    "communication.view",
    "messages.view",
    "media.view",
    "documents.view",
    "rooms.view",
    "equipment.view",
    "rooms.reserve",
    "equipment.reserve",
  ),
};
